Rtru 7571
vue-rt-style/vue-rt-style-kit-molecules pull request #22
Opened 2020-10-26 11:29 UTC by molodbrit

Внёс правки по замечаниям

2020-10-27 08:36 UTC, cryingjoker requested changes
нет( не пущу... много ошибок и непоняток... алгоритм анимации не понятно зачем такой выбран? в чем его рациональность? 
код не прогонялся на pages - его там нет.

2020-10-27 08:36 UTC, cryingjoker commented on src/components/BannerV2/BannerSkeleton.vue
> +<template functional>
зачем перешел на странный рендер через темплейт если можно было просто добавить 
functional: true ?

https://ru.vuejs.org/v2/guide/render-function.html - почитай Функциональные компоненты

`подобных случаях мы можем пометить компоненты как функциональные (опция functional), что означает отсутствие у них состояния (нет реактивных данных) и экземпляра (нет переменной контекста this). Функциональный компонент выглядит так: ` и далее

2020-10-27 08:36 UTC, cryingjoker commented on src/components/BannerV2/BannerSkeleton.vue
> +            <rt-col size="1" t-hide="{true" m-hide="{true"></rt-col>
можешь еще это добавить в pages чтобы проще было смотреть - там у меня ошибка сразу прилетела
`type check failed for prop "tHide". Expected Boolean, got String with value "{true".`

2020-10-27 08:36 UTC, cryingjoker commented on src/css/components/banner-skeleton.styl
> +      padding-top 56vw
зачем vw?

2020-10-27 08:36 UTC, cryingjoker commented on src/css/components/banner-skeleton.styl
> +$waveSizeBanner = 750px
перепиши логику - у тебя 750 на 750 блок который гонится слева на права для двух узких полосок убивает мой мак c i9 и 64 оперативы.

2020-10-27 08:36 UTC, cryingjoker commented on src/css/components/banner-skeleton.styl
> +    transform translate( $waveSizeBanner * 3, $waveSizeBanner * 2 )
зачем в десктопе гнать до самого правого угла если у тебя эти полоски менее 50% ширины? может логику пересмотреть? например сдвиг а потом изменение ширины?

2020-10-27 08:36 UTC, cryingjoker commented on src/components/BannerV2/BannerSkeleton.vue
> +                    <div class="rt-skeleton-banner-header text-block rt-skeleton-banner__wave"></div>
зачем text-block - у него даже css нет?

2020-10-27 08:36 UTC, cryingjoker commented on src/components/BannerV2/BannerSkeleton.vue
> +                    <div class="rt-skeleton-banner-actions-arrows">
ты создал rt-skeleton-banner-actions-arrows в него положил два блока rt-skeleton-banner-actions-arrows-item в и них :after 
почему не просто rt-skeleton-banner-actions-arrows и в него :before и :after ?

2020-10-27 08:36 UTC, cryingjoker commented on src/components/BannerV2/BannerSkeleton.vue
> +                  <div class="rt-skeleton-banner-paginator d-flex">
как вариант - это можно было положить svg в css через background с repeat и убрать 3 dom элемента и большим количеством css

2020-10-27 08:38 UTC, cryingjoker commented
и пожалуйста - jsx темплейты =)

2020-10-28 08:47 UTC, molodbrit commented on src/css/components/banner-skeleton.styl
> +      padding-top 56vw
чтобы размер заглушки точно повторял размер картинки на беннере
![image](https://user-images.githubusercontent.com/43965507/97413074-68e76400-1913-11eb-9420-e1c00d1c2f3f.png)

2020-11-03 11:16 UTC, merged